### ISSUE TITLE
Add save and copy buttons to table

### ISSUE THREAD

**Issue by haesleinhuepf** [0x00b1/napari-features#1]
Hi @0x00b1 ,

would you be interested in adding `Save` and `Copy` buttons to your results table? Just le me know where to put [the code](https://github.com/haesleinhuepf/napari-skimage-regionprops/blob/master/napari_skimage_regionprops/_regionprops.py#L70-L97) and I'll send a PR.

Cheers,
Robert

**Comment by 0x00b1** [comment]
Thanks, @haesleinhuepf! A PR would be awesome. You should add them to `napari_features._dock_widget.DockWidget`.

**Comment by 0x00b1** [comment]
Are there any other interface features you'd like?

**Comment by haesleinhuepf** [comment]
There you go @0x00b1  :-)

> Are there any other interface features you'd like?

I guess, yes. I'm not sure yet how napari-features is supposed to work in practice. I'd like to build a user-interface where users can select features to measure from a label image, e.g.:
![image](https://user-images.githubusercontent.com/12660498/124316569-13381b00-db76-11eb-9578-03ebdf7cd5da.png)

And maybe it is possible to make one user-interface for multiple libraries allowing to do those measurements. Not sure if this is the way to go. Is `napari-features` the right place for that kind of GUI-stuff?

These are my two use cases:

* skimage [regionprops](https://github.com/haesleinhuepf/napari-skimage-regionprops/blob/master/napari_skimage_regionprops/_regionprops.py#L59) would be one way to do it (and skimage is already a dependency) but I'm not sure how to integrated it here.

* A second candidate would be stats from clesperanto. napari-feature should not have clesperanto as dependency. Thus, I'm also wondering how to use the infrastructre of napari-feature [within clesperanto](https://github.com/clEsperanto/napari_pyclesperanto_assistant/blob/master/napari_pyclesperanto_assistant/_statistics_of_labeled_pixels.py#L19-L22).

If we manage to incoroporate both, we can spare tons of code duplication :-)
