### ISSUE TITLE
User interface for configuring which features to measure

### ISSUE THREAD

**Issue by haesleinhuepf** [0x00b1/napari-features#3]
Hi @0x00b1 ,

as just discussed in the napari community meeting: I think a user-interface for selecting which features should be measured would be awesome, A good example for such a GUI is ilastik:
![image](https://user-images.githubusercontent.com/12660498/124791501-66321980-df4c-11eb-97d3-c57b51bfc97f.png)

[source](https://www.ilastik.org/documentation/objects/objects)

**Comment by 0x00b1** [comment]
Thank you very much sir. Banging on this now.

**Comment by 0x00b1** [comment]
@haesleinhuepf merged and released. Thanks again, @haesleinhuepf.
